<a href="https://colab.research.google.com/github/Mahen-Mahindaratne/TensorFlow/blob/main/Reinforcement%20Learning%20with%20Q%20Learning/4_reinforcement_learning_with_q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gym
import numpy as np

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


Let's dive in with a practical example using OpenAI Gym's "FrozenLake" environment:

In [2]:
# Import FrozenLake environment
env = gym.make("FrozenLake-v1")

/usr/local/lib/python3.12/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.12/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [3]:
# Define action space and observation space
action_space = env.action_space.n
state_space = env.observation_space.n

In [4]:
# Hyperparameters
alpha = 0.1  # Learning rate
gamma = 0.9  # Discount factor
epsilon = 0.1  # Exploration rate

In [5]:
# Initialize Q-table with zeros
Q = np.zeros((state_space, action_space))

In [7]:
# Iterate for specified number of episodes
for episode in range(100000):
  # Initialize starting state
    state = env.reset()

  # Episode loop
    while True:

        # Choose action based on Q-table and exploration policy
        if np.random.rand() < epsilon:
            action = env.action_space.sample()  # Explore!
        else:
            action = np.argmax(Q[state])  # Exploit!

        # Take action and observe new state and reward
        new_state, reward, done, _ = env.step(action)

        # Update Q-table
        max_future_Q = np.max(Q[new_state])
        Q[state, action] += alpha * (reward + gamma * max_future_Q - Q[state, action])

        # Check if episode finished
        if done:
            break

        # Update state for next iteration
        state = new_state

In [8]:
# Print final Q-table
print(Q)

[[0.0561727  0.05569008 0.07195705 0.05321645]
 [0.03134542 0.03023725 0.04162084 0.05272864]
 [0.05554541 0.0599086  0.04663854 0.04659296]
 [0.03137157 0.03425235 0.03170302 0.04804967]
 [0.10166119 0.05461266 0.05010054 0.04341869]
 [0.         0.         0.         0.        ]
 [0.04270091 0.05153866 0.12574607 0.02092734]
 [0.         0.         0.         0.        ]
 [0.09114324 0.10540368 0.07526685 0.15197682]
 [0.12507034 0.2709417  0.10675699 0.14905179]
 [0.35535373 0.19730801 0.1535574  0.10120143]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.20245309 0.1570784  0.39356691 0.31100971]
 [0.38858648 0.65242329 0.49822876 0.49494151]
 [0.         0.         0.         0.        ]]


**Running the code:**

This code trains the agent to navigate the FrozenLake environment efficiently. It starts with random exploration and gradually learns the optimal path, reflected in the updated Q-table.

**Remember:**

- This is a simplified example; real-world applications often involve more complex environments, larger state-action spaces, and advanced techniques.
    
- Explore different hyperparameters and environments to gain a deeper understanding of Q-learning's capabilities and limitations.

